# Generated by Django 2.2.21 on 2021-08-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GU_CODE', models.IntegerField(verbose_name='지역코드')),
                ('DONG_NAME', models.CharField(max_length=256, verbose_name='법정동')),
                ('TRADE_DATE', models.CharField(max_length=32, verbose_name='거래일')),
                ('APT_NAME', models.CharField(max_length=256, verbose_name='아파트')),
                ('JI_NUM', models.CharField(max_length=64, verbose_name='지번')),
                ('AREA_SIZE', models.FloatField(verbose_name='전용면적')),
                ('FLOOR', models.IntegerField(verbose_name='층')),
                ('BUILT_YEAR', models.IntegerField(verbose_name='건축년도')),
                ('TRADE_PRICE', models.IntegerField(verbose_name='거래금액')),
            ],
        ),
    ]
