# Generated by Django 2.2.21 on 2021-08-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trading',
            name='TRADE_MONTH',
            field=models.IntegerField(default=0, verbose_name='거래월'),
            preserve_default=False,
        ),
    ]
